version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Istanbul"
    labels:
      - "dependencies"
      - "maven"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
